import os

CLIENT_TOKEN = os.environ['CLIENT_TOKEN']
DB_USER = os.environ['POSTGRES_USER']
DB_PASSWORD = os.environ['POSTGRES_PASSWORD']
DB_NAME = os.environ['POSTGRES_DB']
DB_ADDRESS = os.environ['POSTGRES_ADDRESS']
CONN_STRING = f"postgres://{DB_USER}:{DB_PASSWORD}@{DB_ADDRESS}:5432/{DB_NAME}"
